title: Desiree Arthuso
description: Arquiteta & Urbanista
site_title: 'Desiree Arthuso'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: desireearthuso
blog_url: https://www.nagekar.com
email: desireearthuso.contato@gmail.com
# keybase_username: abhn
# twitter_username: abhn_
# reddit_username: abhn

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics:
